<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WeChatVoice.Application\WeChatVoice.Application.csproj" />
    <ProjectReference Include="..\WeChatVoice.Core\WeChatVoice.Core.csproj" />
    <ProjectReference Include="..\WeChatVoice.Infrastructure\WeChatVoice.Infrastructure.csproj" />
    <ProjectReference Include="..\WeChatVoice.KeyProfileMetadata\WeChatVoice.KeyProfileMetadata.csproj" />
    <ProjectReference Include="..\WeChatVoice.Windows\WeChatVoice.Windows.csproj" />
  </ItemGroup>

</Project>
