using System.Text.Json;

namespace WeChatVoice.Workflows.Broker;

/// <summary>
/// Hash-bound publish manifest for the Key Broker binary, generated by
/// build/GenerateBrokerBundleManifest.ps1 and verified at runtime by
/// <see cref="ReleaseBrokerTrustPolicy"/>. It mirrors the SQLCipher worker
/// bundle manifest shape and additionally pins the release publisher.
/// </summary>
public sealed record BrokerBundleManifest(
    string BrokerExeSha256,
    string? DepsFile,
    string? DepsSha256,
    string? RuntimeConfigFile,
    string? RuntimeConfigSha256,
    string? PublisherThumbprint);

public static class BrokerBundleManifestLoader
{
    private static readonly JsonSerializerOptions ManifestOptions = new(JsonSerializerDefaults.Web);

    public static BrokerBundleManifest? TryLoad(string installDirectory)
    {
        var manifestPath = Path.Combine(installDirectory, "WeChatVoice.KeyBroker.bundle.json");
        if (!File.Exists(manifestPath) || (File.GetAttributes(manifestPath) & FileAttributes.ReparsePoint) != 0)
        {
            return null;
        }

        try
        {
            using var stream = new FileStream(manifestPath, FileMode.Open, FileAccess.Read, FileShare.Read, 16 * 1024, FileOptions.SequentialScan);
            return JsonSerializer.Deserialize<BrokerBundleManifest>(stream, ManifestOptions);
        }
        catch (JsonException)
        {
            return null;
        }
    }

    /// <summary>
    /// Verifies every referenced sidecar is a non-reparse relative file under
    /// the install directory whose SHA-256 matches the manifest.
    /// </summary>
    public static bool VerifySidecars(string installDirectory, BrokerBundleManifest manifest)
    {
        var prefix = Path.GetFullPath(installDirectory).TrimEnd(Path.DirectorySeparatorChar) + Path.DirectorySeparatorChar;
        foreach (var (relative, expectedHash) in new[]
                 {
                     (manifest.DepsFile, manifest.DepsSha256),
                     (manifest.RuntimeConfigFile, manifest.RuntimeConfigSha256),
                 })
        {
            if (string.IsNullOrWhiteSpace(relative) && string.IsNullOrWhiteSpace(expectedHash))
            {
                continue;
            }

            if (string.IsNullOrWhiteSpace(relative) || string.IsNullOrWhiteSpace(expectedHash) || Path.IsPathRooted(relative))
            {
                return false;
            }

            var path = Path.GetFullPath(Path.Combine(installDirectory, relative));
            if (!path.StartsWith(prefix, StringComparison.OrdinalIgnoreCase) || !File.Exists(path))
            {
                return false;
            }

            if ((File.GetAttributes(path) & FileAttributes.ReparsePoint) != 0)
            {
                return false;
            }

            using var stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read, 128 * 1024, FileOptions.SequentialScan);
            using var hasher = System.Security.Cryptography.SHA256.Create();
            var actual = Convert.ToHexString(hasher.ComputeHash(stream)).ToLowerInvariant();
            if (!string.Equals(actual, expectedHash, StringComparison.OrdinalIgnoreCase))
            {
                return false;
            }
        }

        return true;
    }
}
